// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjVJhAygiP7f-EVn5IUPWYTkHt-aoxzkI',
    appId: '1:332618593014:web:0d117348245a7f359772d7',
    messagingSenderId: '332618593014',
    projectId: 'fir-prm',
    authDomain: 'fir-prm.firebaseapp.com',
    databaseURL:
        'https://fir-prm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-prm.firebasestorage.app',
    measurementId: 'G-PPBWSWHZ8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZD0SDxf42OjI7EtgeUVzPodfhZQwyfUc',
    appId: '1:332618593014:android:7cf690fee4f307019772d7',
    messagingSenderId: '332618593014',
    projectId: 'fir-prm',
    databaseURL:
        'https://fir-prm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-prm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv6dviSpIxxAbETIB0z0N7t296LtPl8GQ',
    appId: '1:332618593014:ios:db42b22db9fe32f09772d7',
    messagingSenderId: '332618593014',
    projectId: 'fir-prm',
    databaseURL:
        'https://fir-prm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-prm.firebasestorage.app',
    androidClientId:
        '332618593014-9il4a6m6ftmjced301ho4on1drt7bk3s.apps.googleusercontent.com',
    iosClientId:
        '332618593014-6qfejbja6047s61gp6f6ri2qm82ao8mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneMangaAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv6dviSpIxxAbETIB0z0N7t296LtPl8GQ',
    appId: '1:332618593014:ios:db42b22db9fe32f09772d7',
    messagingSenderId: '332618593014',
    projectId: 'fir-prm',
    databaseURL:
        'https://fir-prm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-prm.firebasestorage.app',
    androidClientId:
        '332618593014-9il4a6m6ftmjced301ho4on1drt7bk3s.apps.googleusercontent.com',
    iosClientId:
        '332618593014-6qfejbja6047s61gp6f6ri2qm82ao8mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneMangaAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjVJhAygiP7f-EVn5IUPWYTkHt-aoxzkI',
    appId: '1:332618593014:web:01d23dd4b866d3b69772d7',
    messagingSenderId: '332618593014',
    projectId: 'fir-prm',
    authDomain: 'fir-prm.firebaseapp.com',
    databaseURL:
        'https://fir-prm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-prm.firebasestorage.app',
    measurementId: 'G-152DCW3DS7',
  );
}
